In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


# Introduction to Tensors

### Creating tensors

PyTorch tensors are created using torch.tensor()

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# get the tensor back to python int
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7,7])

In [7]:
vector

tensor([7, 7])

In [8]:
# check the dim as no. of square bracket
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
matrix = torch.tensor([[7,8],
                       [4,6]])

In [11]:
matrix

tensor([[7, 8],
        [4, 6]])

In [12]:
matrix.ndim

2

In [13]:
matrix[0]

tensor([7, 8])

In [14]:
matrix.shape

torch.Size([2, 2])

# Random Tensors

### Why Random Tensors
Random tensors are important because the way many neural networks learn is that they start with tensors full of random adjust those random numbers to better represent the data

In [15]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,128,128)

In [16]:
random_tensor

tensor([[[0.3460, 0.5826, 0.6213,  ..., 0.6338, 0.9892, 0.3160],
         [0.4149, 0.0047, 0.9930,  ..., 0.3131, 0.8999, 0.4261],
         [0.7612, 0.3396, 0.8619,  ..., 0.2587, 0.1907, 0.9463],
         ...,
         [0.8825, 0.2056, 0.8618,  ..., 0.5871, 0.6713, 0.6059],
         [0.1518, 0.7697, 0.5761,  ..., 0.6249, 0.4276, 0.3590],
         [0.5213, 0.0922, 0.6709,  ..., 0.0434, 0.3802, 0.5685]],

        [[0.4583, 0.4464, 0.5576,  ..., 0.5550, 0.9556, 0.1379],
         [0.0548, 0.7047, 0.7784,  ..., 0.1419, 0.0553, 0.2998],
         [0.2275, 0.6565, 0.7042,  ..., 0.7181, 0.6586, 0.4793],
         ...,
         [0.4666, 0.3851, 0.7304,  ..., 0.3012, 0.6772, 0.1153],
         [0.6573, 0.6317, 0.8555,  ..., 0.0748, 0.2914, 0.4668],
         [0.4761, 0.2708, 0.9437,  ..., 0.3705, 0.2837, 0.6458]],

        [[0.4683, 0.3465, 0.7246,  ..., 0.3996, 0.1410, 0.7774],
         [0.0016, 0.2489, 0.7544,  ..., 0.2604, 0.7833, 0.9298],
         [0.5732, 0.0842, 0.9323,  ..., 0.0712, 0.8718, 0.

#**Some Crazy Stuff**

In [17]:
# import torchvision.transforms as transforms
# from PIL import Image
# to_pil = transforms.ToPILImage()
# image = to_pil(random_tensor)

# image.save("random_image.png")
# image.show()

In [18]:
# import torch
# import numpy as np
# from PIL import Image

# H, W = 256, 256
# tensor = torch.zeros(3, H, W)  # Black RGB image

# # Circle parameters
# cx, cy = W // 2, H // 2
# radius = 60

# # Create meshgrid of coordinates
# y, x = torch.meshgrid(torch.arange(H), torch.arange(W), indexing='ij')

# # Create circle mask
# mask = (x - cx)**2 + (y - cy)**2 < radius**2

# # Set the circle area to white (255 in all RGB channels)
# tensor[:, mask] = 1.0  # or 255 if using uint8 later

# # Convert to image
# image = transforms.ToPILImage()(tensor)
# image.show()


In [19]:
# freq = 10.0
# pattern = torch.sin(x.float() / freq) + torch.cos(y.float() / freq)
# normalized = (pattern - pattern.min()) / (pattern.max() - pattern.min())

# # Expand to 3 channels
# tensor = normalized.unsqueeze(0).repeat(3, 1, 1)
# image = transforms.ToPILImage()(tensor)
# image.save("shape.png")
# image.show()


## creating the tensors of all zeros

In [20]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones = torch.ones(size=(3,4))

In [22]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
data = torch.arange(0,10,0.5)

In [25]:
like_zeros = torch.zeros_like(input = data)

In [26]:
like_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
# default datatype of pytorch is float_32_tensor
float_16_tensor = float_32_tensor.type(torch.float16)

In [30]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

##Getting information from tensors (tensor attributes)
1.Tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype

2.Tensors not right shape - to get shape from a tensor, can use tensor.shape

3.Tensors not on the right device - to get device from a tensor, can use tensor.device

In [32]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9319, 0.9604, 0.6948, 0.0726],
        [0.8947, 0.7395, 0.0234, 0.5581],
        [0.0084, 0.2273, 0.5826, 0.9258]])

In [33]:
print(some_tensor)
print(f"DataType of tensor :{some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device of tensor : {some_tensor.device}")

tensor([[0.9319, 0.9604, 0.6948, 0.0726],
        [0.8947, 0.7395, 0.0234, 0.5581],
        [0.0084, 0.2273, 0.5826, 0.9258]])
DataType of tensor :torch.float32
Shape of tensor : torch.Size([3, 4])
Device of tensor : cpu


### Manipulation Tensors (tensor operations)
#### Tensor opitons include :
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [34]:
# create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [35]:
tensor*10

tensor([10, 20, 30])

In [36]:
tensor-10

tensor([-9, -8, -7])

In [37]:
torch.mul(tensor,10) # pytorch inbuilt function

tensor([10, 20, 30])

## Matrix Multiplication
Two main ways of performing multiplication in neural networks and deep learning

1. Element wise muliplication
2. Matrix multiplication

For more information visit :https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplicaiton needs to satisfy:
1. The **inner dimensions** must match
2. **@** or **mm** used instead of **matmul** but matmul is preferred

In [38]:
# Element Wise Multiplication
print(tensor,"*",tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [39]:
torch.matmul(tensor,tensor)

tensor(14)

In [40]:
## Time difference between the function and normal method
%%time
value=0
for i in range(len(tensor)):
  value += tensor[i]+tensor[i]
print(value)

tensor(12)
CPU times: user 552 µs, sys: 923 µs, total: 1.47 ms
Wall time: 1.55 ms


In [41]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 301 µs, sys: 49 µs, total: 350 µs
Wall time: 266 µs


tensor(14)

#### **Conclusion :** time difference between the manual calculation and the inbuilt pytorch function

**one of the most common errors in the deep learning is shape error**

To fix the tensor shape issues we can manpulate the shape of one of our tensors using a **Transpose**

A *Transpose* switches the axes or dimensions of a given tensor

In [42]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [43]:
x.type(torch.float32).mean()

tensor(45.)

In [44]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [45]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
# Find the position in tensor that has the minimum value with argmin() ->
# return the index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [47]:
x.argmax()

tensor(9)

## Reshaping,stacking ,squeezing and unsqueezing tensors
* Reshaping - rephapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shpae butkeep teh same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [48]:
import torch
x = torch.arange(1,10)
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [49]:
x_reshaped = x.reshape(9,1) # added the extra dimensions
x_reshaped,x_reshaped.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [50]:
# change the view
z = x.view(1,9)
z,z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [51]:
# Changing z changes x (because a view of tensor shares the same memory as he original)
z[:,0]=5
z

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [52]:
x

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
x_stacked = torch.stack([x,x,x,x],dim=1)

In [54]:
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [57]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

Previous tensor: tensor([[5],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
Previous shape: torch.Size([9, 1])


In [58]:
# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


New tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


In [59]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

Previous target: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])


In [60]:
# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


New tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])


In [61]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

In [62]:
# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

In [63]:
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [64]:
x_original[0,0,0] = 728218
x_original[0,0,0] ,x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

In [65]:
# indexing(selecting data from tensors)
# create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [66]:
# let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [67]:
x[0][0][0]

tensor(1)

In [68]:
x[:,0]

tensor([[1, 2, 3]])

## PyTorch tensors & numpy
NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [69]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1,8)
tensor = torch.from_numpy(array)
array,tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [70]:
array.dtype,tensor.dtype

(dtype('int64'), torch.int64)

In [71]:
# Change the value of array
array = array+1
array,tensor

(array([2, 3, 4, 5, 6, 7, 8]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [72]:
# tensor = torch.from_numpy(array)
# warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
# array, tensor


In [74]:
# tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

##Reproducbility (trying to take random out of random)
In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed.**

Essentially what the random seed does is "flavour" the randomness.

In [75]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5787, 0.0688, 0.6788, 0.1635],
        [0.0751, 0.5998, 0.0347, 0.4086],
        [0.9517, 0.9010, 0.3875, 0.4320]])
tensor([[0.6797, 0.3623, 0.9517, 0.1997],
        [0.3806, 0.8614, 0.1048, 0.4453],
        [0.3986, 0.0265, 0.9210, 0.8170]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [76]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [77]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [81]:
# the below output changes when you use the GPU to run
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

In [82]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [83]:
# Count number of devices
torch.cuda.device_count()

0

In [84]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [85]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [86]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

array([1, 2, 3])

In [87]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [88]:
tensor_on_gpu

tensor([1, 2, 3])